import { useState, useRef, useEffect } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { motion, AnimatePresence } from "framer-motion";
import {
  Search, Upload, FileText, FileSpreadsheet,
  AlertCircle, X, Monitor,
  MousePointer, Brain, Zap, Shield,
  ChevronDown, ChevronRight, Image as ImageIcon,
  ArrowLeft, CheckCircle2, Link2,
} from "lucide-react";
import { cn } from "@/lib/utils";
import aetherLogo from "@/assets/aether-logo.png";
import { runAudit, type RichScreenAudit, type RichAuditCategory, type RichAuditIssue } from "@/lib/api";
import { supabase } from "@/lib/supabase";
import { useAuth } from "@/contexts/AuthContext";

// ─── Types ────────────────────────────────────────────────────────────────────

type AuditPhase = "setup" | "running" | "results";
type InputTab   = "upload" | "link";
type SevFilter  = "all" | "high" | "medium" | "low";
type IssueType  = "usability" | "cognitive" | "interaction" | "emotional" | "system";

// ─── Constants ────────────────────────────────────────────────────────────────

const INDUSTRIES = ["SaaS", "E-commerce", "Fintech", "Healthcare", "EdTech", "Marketplace", "Mobile App", "Other"];

const ISSUE_TYPE_CONFIG: Record<IssueType, { label: string; Icon: React.ElementType; color: string }> = {
  usability:   { label: "Usability",      Icon: MousePointer, color: "#F43F5E" },
  cognitive:   { label: "Cognitive Load", Icon: Brain,        color: "#F59E0B" },
  interaction: { label: "Interaction",    Icon: Zap,          color: "#3B82F6" },
  emotional:   { label: "Trust & Tone",   Icon: Shield,       color: "#8B5CF6" },
  system:      { label: "System Gaps",    Icon: AlertCircle,  color: "#64748B" },
};

const SEV_STYLE: Record<string, { dot: string; badge: string; text: string }> = {
  High:   { dot: "#F43F5E", badge: "#FFF1F2", text: "#BE123C" },
  Medium: { dot: "#F59E0B", badge: "#FFFBEB", text: "#B45309" },
  Low:    { dot: "#3B82F6", badge: "#EFF6FF", text: "#1D4ED8" },
};

// ─── Utilities ────────────────────────────────────────────────────────────────

function getAllIssues(screens: RichScreenAudit[]) {
  return screens.flatMap(s => s.categories.flatMap(c => c.issues));
}

function scoreColor(score: number): string {
  if (score >= 75) return "#059669";
  if (score >= 60) return "#D97706";
  return "#DC2626";
}

function downloadBlob(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

function exportExcel(screens: RichScreenAudit[]) {
  const header = ["Screen", "Category", "Severity", "Issue", "Description", "Recommendation"];
  const rows = screens.flatMap(s => s.categories.flatMap(c =>
    c.issues.map(i => [s.name, ISSUE_TYPE_CONFIG[c.type as IssueType]?.label ?? c.type, i.severity, i.title, i.description, i.recommendation])
  ));
  const csv = "\uFEFF" + [header, ...rows].map(r => r.map(v => `"${String(v).replace(/"/g, '""')}"`).join(",")).join("\r\n");
  downloadBlob(csv, "UX_Audit_Report.csv", "text/csv;charset=utf-8;");
}

function exportPDF(screens: RichScreenAudit[]) {
  const allIssues = getAllIssues(screens);
  const high = allIssues.filter(i => i.severity === "High").length;
  const avg = screens.length ? Math.round(screens.reduce((a, s) => a + s.score, 0) / screens.length) : 0;
  const rows = screens.flatMap(s => s.categories.flatMap(c =>
    c.issues.filter(i => i.severity === "High").map(i =>
      `<tr><td>${s.name}</td><td>${ISSUE_TYPE_CONFIG[c.type as IssueType]?.label ?? c.type}</td><td style="color:#BE123C;font-weight:600">High</td><td>${i.title}</td><td>${i.recommendation}</td></tr>`
    )
  )).join("");
  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(`<!DOCTYPE html><html><head><meta charset="utf-8"/><title>UX Audit Report</title>
  <style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,sans-serif;padding:48px;color:#0F172A;font-size:13px}
  h1{font-size:22px;font-weight:700;margin-bottom:6px}p.sub{color:#6B7280;margin-bottom:32px}
  .stats{display:flex;gap:20px;margin-bottom:32px}.stat{border:1px solid #E5E7EB;border-radius:12px;padding:14px 20px}
  .stat-v{font-size:26px;font-weight:700;color:#0F172A}.stat-l{font-size:11px;color:#6B7280;text-transform:uppercase;letter-spacing:.06em;margin-top:2px}
  h2{font-size:15px;font-weight:600;margin-bottom:12px;color:#374151}
  table{width:100%;border-collapse:collapse}th{text-align:left;padding:9px 12px;background:#F9FAFB;border-bottom:2px solid #E5E7EB;font-size:11px;text-transform:uppercase;color:#6B7280}
  td{padding:10px 12px;border-bottom:1px solid #F1F5F9;vertical-align:top}</style>
  </head><body>
  <h1>UX Audit Report</h1><p class="sub">Generated by Aether · ${screens.length} screens analysed</p>
  <div class="stats">
    <div class="stat"><div class="stat-v">${allIssues.length}</div><div class="stat-l">Total Issues</div></div>
    <div class="stat"><div class="stat-v" style="color:#BE123C">${high}</div><div class="stat-l">High Severity</div></div>
    <div class="stat"><div class="stat-v">${avg}/100</div><div class="stat-l">Avg UX Score</div></div>
  </div>
  <h2>Critical Issues</h2>
  <table><thead><tr><th>Screen</th><th>Category</th><th>Severity</th><th>Issue</th><th>Fix</th></tr></thead><tbody>${rows}</tbody></table>
  </body></html>`);
  win.document.close(); win.focus(); setTimeout(() => win.print(), 300);
}

// ─── Sub-components ───────────────────────────────────────────────────────────

function UploadZone({ files, onFiles }: { files: File[]; onFiles: (f: File[]) => void }) {
  const [isDragging, setIsDragging] = useState(false);
  const ref = useRef<HTMLInputElement>(null);
  return (
    <div className="space-y-3">
      <div
        onDragOver={e => { e.preventDefault(); setIsDragging(true); }}
        onDragLeave={() => setIsDragging(false)}
        onDrop={e => { e.preventDefault(); setIsDragging(false); onFiles([...files, ...Array.from(e.dataTransfer.files)]); }}
        onClick={() => ref.current?.click()}
        className="rounded-2xl px-8 py-12 flex flex-col items-center gap-3 cursor-pointer transition-all hover:border-[#9CA3AF] hover:bg-[#F9FAFB]"
        style={{ border: `2px dashed ${isDragging ? "#6366F1" : "#D1D5DB"}`, background: isDragging ? "#F5F3FF" : "#FAFAFA" }}
      >
        <div className="h-12 w-12 rounded-xl flex items-center justify-center" style={{ background: "#EEF2FF" }}>
          <Upload className="h-5 w-5" style={{ color: "#6366F1" }} strokeWidth={1.5} />
        </div>
        <div className="text-center space-y-1">
          <p className="text-sm font-medium" style={{ color: "#0F172A" }}>
            {isDragging ? "Drop your screens here" : "Drop screens here, or click to upload"}
          </p>
          <p className="text-xs" style={{ color: "#6B7280" }}>PNG, JPG, WebP, PDF supported · Multiple files allowed</p>
        </div>
        <input ref={ref} type="file" multiple accept="image/*,.pdf" className="hidden"
          onChange={e => e.target.files && onFiles([...files, ...Array.from(e.target.files)])} />
      </div>
      {files.length > 0 && (
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
          {files.map((f, i) => (
            <div key={i} className="flex items-center gap-2 rounded-xl px-3 py-2" style={{ border: "1px solid #E5E7EB", background: "#FFFFFF" }}>
              <ImageIcon className="h-3.5 w-3.5 shrink-0" style={{ color: "#9CA3AF" }} strokeWidth={1.5} />
              <span className="text-[11px] truncate flex-1" style={{ color: "#374151" }}>{f.name}</span>
              <button onClick={e => { e.stopPropagation(); onFiles(files.filter((_, j) => j !== i)); }}>
                <X className="h-3 w-3" style={{ color: "#9CA3AF" }} strokeWidth={2} />
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function IssueCard({ issue }: { issue: RichAuditIssue }) {
  const s = SEV_STYLE[issue.severity] ?? SEV_STYLE.Medium;
  return (
    <div className="flex items-start gap-3 py-3.5 border-b last:border-0" style={{ borderColor: "#F1F5F9" }}>
      <div className="h-2 w-2 rounded-full mt-2 shrink-0" style={{ background: s.dot }} />
      <div className="flex-1 min-w-0 space-y-1.5">
        <div className="flex items-start gap-2 flex-wrap">
          <span className="text-sm font-semibold" style={{ color: "#0F172A" }}>{issue.title}</span>
          <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full" style={{ background: s.badge, color: s.text }}>
            {issue.severity}
          </span>
        </div>
        <p className="text-xs leading-relaxed" style={{ color: "#6B7280" }}>{issue.description}</p>
        <div className="flex items-start gap-1.5 text-xs rounded-lg px-3 py-2" style={{ background: "#F8FAFC", border: "1px solid #E5E7EB", color: "#374151" }}>
          <ChevronRight className="h-3 w-3 mt-0.5 shrink-0" style={{ color: "#9CA3AF" }} strokeWidth={1.5} />
          {issue.recommendation}
        </div>
      </div>
    </div>
  );
}

function IssueCategoryBlock({ category, sevFilter }: { category: RichAuditCategory; sevFilter: SevFilter }) {
  const [open, setOpen] = useState(true);
  const cfg = ISSUE_TYPE_CONFIG[category.type as IssueType] ?? { label: category.type, Icon: AlertCircle, color: "#64748B" };
  const visible = category.issues.filter(i => sevFilter === "all" || i.severity.toLowerCase() === sevFilter);
  if (visible.length === 0) return null;
  const highCount = visible.filter(i => i.severity === "High").length;
  return (
    <div style={{ borderBottom: "1px solid #F1F5F9" }} className="last:border-0">
      <button onClick={() => setOpen(o => !o)} className="w-full flex items-center gap-2.5 px-5 py-3 hover:bg-[#F9FAFB] transition-colors">
        <div className="h-2 w-2 rounded-full shrink-0" style={{ background: cfg.color }} />
        <cfg.Icon className="h-3.5 w-3.5 shrink-0" style={{ color: cfg.color }} strokeWidth={1.5} />
        <span className="text-xs font-semibold flex-1 text-left" style={{ color: "#0F172A" }}>{cfg.label}</span>
        <div className="flex items-center gap-1.5">
          {highCount > 0 && (
            <span className="text-[9px] font-bold px-1.5 py-0.5 rounded-full" style={{ background: "#FFF1F2", color: "#BE123C" }}>
              {highCount} High
            </span>
          )}
          <span className="text-[10px]" style={{ color: "#9CA3AF" }}>{visible.length} issue{visible.length !== 1 ? "s" : ""}</span>
          {open
            ? <ChevronDown className="h-3.5 w-3.5 ml-1" style={{ color: "#9CA3AF" }} strokeWidth={1.5} />
            : <ChevronRight className="h-3.5 w-3.5 ml-1" style={{ color: "#9CA3AF" }} strokeWidth={1.5} />
          }
        </div>
      </button>
      <AnimatePresence initial={false}>
        {open && (
          <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }} transition={{ duration: 0.15 }} className="overflow-hidden">
            <div className="px-5 pb-1">
              {visible.map(issue => <IssueCard key={issue.id} issue={issue} />)}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

function ScreenAuditCard({ screen, sevFilter, previewUrl }: { screen: RichScreenAudit; sevFilter: SevFilter; previewUrl?: string }) {
  const allIssues = screen.categories.flatMap(c => c.issues);
  const highCount = allIssues.filter(i => i.severity === "High").length;
  const color = scoreColor(screen.score);

  return (
    <div className="rounded-2xl overflow-hidden" style={{ border: "1px solid #E5E7EB" }}>
      {/* Header */}
      <div className="px-5 py-4 flex items-center gap-4 flex-wrap" style={{ borderBottom: "1px solid #E5E7EB", background: "#FAFAFA" }}>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <h3 className="text-sm font-bold" style={{ color: "#0F172A" }}>{screen.name}</h3>
            <span className="text-[10px] px-2 py-0.5 rounded-full" style={{ background: "#F1F5F9", color: "#64748B" }}>{screen.persona}</span>
          </div>
          <p className="text-xs mt-0.5" style={{ color: "#6B7280" }}>{allIssues.length} issues · {highCount} high severity</p>
        </div>
        <span className="text-sm font-bold px-3 py-1 rounded-lg shrink-0" style={{ color, background: `${color}18` }}>
          {screen.score}/100
        </span>
      </div>

      {/* Preview */}
      <div className="px-5 py-4" style={{ borderBottom: "1px solid #F1F5F9" }}>
        <div className="aspect-video rounded-xl overflow-hidden flex items-center justify-center"
          style={{ background: "#F8FAFC", border: "1px solid #E5E7EB" }}>
          {previewUrl ? (
            <img src={previewUrl} alt={screen.name} className="w-full h-full object-contain" />
          ) : (
            <div className="flex flex-col items-center gap-2">
              <Monitor className="h-8 w-8" style={{ color: "#CBD5E1" }} strokeWidth={1} />
              <span className="text-xs" style={{ color: "#94A3B8" }}>{screen.name}</span>
            </div>
          )}
        </div>
      </div>

      {/* Categories */}
      <div style={{ background: "#FFFFFF" }}>
        {screen.categories.map(cat => (
          <IssueCategoryBlock key={cat.type} category={cat} sevFilter={sevFilter} />
        ))}
      </div>
    </div>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────

export default function UXAuditTool() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { user } = useAuth();

  // Setup state
  const [projectName, setProjectName] = useState("");
  const [projectDesc, setProjectDesc] = useState("");
  const [industry,    setIndustry]    = useState("");
  const [inputTab,    setInputTab]    = useState<InputTab>("upload");
  const [files,       setFiles]       = useState<File[]>([]);
  const [linkValue,   setLinkValue]   = useState("");

  // Results state
  const [phase,      setPhase]      = useState<AuditPhase>("setup");
  const [sevFilter,  setSevFilter]  = useState<SevFilter>("all");
  const [auditData,  setAuditData]  = useState<RichScreenAudit[]>([]);
  const [previews,   setPreviews]   = useState<Record<string, string>>({});
  const [apiError,   setApiError]   = useState<string | null>(null);
  const [savedProjId, setSavedProjId] = useState<string | null>(null);

  const isValidLink = linkValue.startsWith("https://") || linkValue.startsWith("http://");
  const hasInput = files.length > 0 || isValidLink;
  const canRun = projectName.trim().length > 0 && hasInput;

  // Load from URL ?project=<id>
  useEffect(() => {
    const projId = searchParams.get("project");
    if (!projId) return;
    supabase
      .from("agent_runs")
      .select("output_json")
      .eq("project_id", projId)
      .eq("phase", 4)
      .eq("status", "completed")
      .order("created_at", { ascending: false })
      .limit(1)
      .single()
      .then(({ data }) => {
        if (data?.output_json?.audit_rich) {
          setAuditData(data.output_json.audit_rich as RichScreenAudit[]);
          setSavedProjId(projId);
          setPhase("results");
        }
      });
  }, [searchParams]);

  const handleRun = async () => {
    if (!canRun || !user) return;
    setPhase("running");
    setApiError(null);

    // Build previews
    const previewMap: Record<string, string> = {};
    files.forEach(f => {
      const name = f.name.replace(/\.[^/.]+$/, "");
      previewMap[name] = URL.createObjectURL(f);
    });
    setPreviews(prev => { Object.values(prev).forEach(u => URL.revokeObjectURL(u)); return previewMap; });

    try {
      // Create Supabase project
      const { data: proj, error: projErr } = await supabase.from("projects").insert({
        user_id: user.id,
        name: projectName,
        description: projectDesc || null,
        product_type: "ux_audit",
        domain: industry || null,
        status: "active",
        current_phase: 4,
      }).select().single();

      if (projErr || !proj) throw new Error(projErr?.message ?? "Failed to create project");
      setSavedProjId(proj.id);

      const res = await runAudit(proj.id, files, isValidLink ? linkValue : "", projectDesc);
      setAuditData(res.audit_rich as RichScreenAudit[]);
      setPhase("results");
    } catch (err: unknown) {
      setApiError(err instanceof Error ? err.message : "Audit failed. Make sure backend is running on http://localhost:8000");
      setPhase("setup");
    }
  };

  const allIssues = getAllIssues(auditData);
  const highCount = allIssues.filter(i => i.severity === "High").length;
  const avgScore  = auditData.length ? Math.round(auditData.reduce((a, s) => a + s.score, 0) / auditData.length) : 0;

  return (
    <div className="min-h-screen" style={{ background: "#FFFFFF" }}>

      {/* Header */}
      <header className="sticky top-0 z-10 flex items-center justify-between px-6 py-4"
        style={{ background: "#FFFFFF", borderBottom: "1px solid #E5E7EB" }}>
        <div className="flex items-center gap-2">
          <img src={aetherLogo} alt="Aether" className="h-6 w-6 rounded-md object-contain"
            style={{ background: "#EEF2FF", padding: "2px" }} />
          <span className="text-sm font-semibold" style={{ color: "#0F172A" }}>Aether</span>
        </div>
        <button onClick={() => navigate("/dashboard")}
          className="flex items-center gap-1.5 text-xs transition-colors hover:opacity-70"
          style={{ color: "#6B7280" }}>
          <ArrowLeft className="h-3.5 w-3.5" strokeWidth={1.5} />
          Back to Dashboard
        </button>
      </header>

      <div className="max-w-2xl mx-auto px-6 py-12">
        <AnimatePresence mode="wait">

          {/* Setup */}
          {phase === "setup" && (
            <motion.div key="setup" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: 0.2 }}>
              <div className="mb-10">
                <h1 className="text-3xl font-bold mb-2" style={{ color: "#0F172A" }}>UX Audit</h1>
                <p className="text-base" style={{ color: "#6B7280" }}>
                  Analyze your product experience, detect usability issues, and uncover friction instantly.
                </p>
              </div>

              <div className="space-y-5">
                {/* Project Name */}
                <div className="space-y-1.5">
                  <label className="text-xs font-semibold" style={{ color: "#374151" }}>
                    Project Name <span style={{ color: "#F43F5E" }}>*</span>
                  </label>
                  <input
                    value={projectName} onChange={e => setProjectName(e.target.value)}
                    placeholder="e.g. Housewise, Fintech App, SaaS Dashboard"
                    className="w-full rounded-xl px-4 py-3 text-sm outline-none transition-all"
                    style={{ border: "1px solid #E5E7EB", color: "#0F172A", background: "#FFFFFF" }}
                    onFocus={e => (e.target.style.borderColor = "#6366F1")}
                    onBlur={e => (e.target.style.borderColor = "#E5E7EB")}
                  />
                </div>

                {/* Description */}
                <div className="space-y-1.5">
                  <label className="text-xs font-semibold" style={{ color: "#374151" }}>
                    Description <span className="font-normal" style={{ color: "#9CA3AF" }}>— optional</span>
                  </label>
                  <textarea
                    value={projectDesc} onChange={e => setProjectDesc(e.target.value)}
                    placeholder="Briefly describe your product, target users, and context"
                    rows={3}
                    className="w-full rounded-xl px-4 py-3 text-sm outline-none resize-none transition-all"
                    style={{ border: "1px solid #E5E7EB", color: "#0F172A", background: "#FFFFFF" }}
                    onFocus={e => (e.target.style.borderColor = "#6366F1")}
                    onBlur={e => (e.target.style.borderColor = "#E5E7EB")}
                  />
                </div>

                {/* Industry */}
                <div className="space-y-1.5">
                  <label className="text-xs font-semibold" style={{ color: "#374151" }}>
                    Industry <span className="font-normal" style={{ color: "#9CA3AF" }}>— optional</span>
                  </label>
                  <select
                    value={industry} onChange={e => setIndustry(e.target.value)}
                    className="w-full rounded-xl px-4 py-3 text-sm outline-none transition-all appearance-none"
                    style={{ border: "1px solid #E5E7EB", color: industry ? "#0F172A" : "#9CA3AF", background: "#FFFFFF" }}
                    onFocus={e => (e.target.style.borderColor = "#6366F1")}
                    onBlur={e => (e.target.style.borderColor = "#E5E7EB")}
                  >
                    <option value="">Select industry…</option>
                    {INDUSTRIES.map(ind => <option key={ind} value={ind}>{ind}</option>)}
                  </select>
                </div>

                {/* Input method tabs */}
                <div className="rounded-2xl overflow-hidden" style={{ border: "1px solid #E5E7EB" }}>
                  <div className="flex" style={{ borderBottom: "1px solid #E5E7EB", background: "#F9FAFB" }}>
                    {([["upload", "Upload Screens", Upload], ["link", "Paste Link", Link2]] as const).map(([tab, label, Icon]) => (
                      <button key={tab} onClick={() => setInputTab(tab)}
                        className="flex-1 flex items-center justify-center gap-2 py-3 text-xs font-medium transition-all"
                        style={{
                          background: inputTab === tab ? "#FFFFFF" : "transparent",
                          color: inputTab === tab ? "#0F172A" : "#6B7280",
                          borderBottom: inputTab === tab ? "2px solid #6366F1" : "2px solid transparent",
                        }}>
                        <Icon className="h-3.5 w-3.5" strokeWidth={1.5} />
                        {label}
                      </button>
                    ))}
                  </div>
                  <div className="p-5">
                    <AnimatePresence mode="wait">
                      {inputTab === "upload" ? (
                        <motion.div key="upload" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.12 }}>
                          <UploadZone files={files} onFiles={setFiles} />
                        </motion.div>
                      ) : (
                        <motion.div key="link" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.12 }}>
                          <div className="space-y-2">
                            <div className="relative">
                              <Link2 className="absolute left-3.5 top-1/2 -translate-y-1/2 h-4 w-4" style={{ color: "#9CA3AF" }} strokeWidth={1.5} />
                              <input
                                value={linkValue} onChange={e => setLinkValue(e.target.value)}
                                placeholder="https://yourproduct.com"
                                className="w-full rounded-xl pl-10 pr-10 py-3 text-sm outline-none transition-all"
                                style={{ border: "1px solid #E5E7EB", color: "#0F172A", background: "#FFFFFF" }}
                                onFocus={e => (e.target.style.borderColor = "#6366F1")}
                                onBlur={e => (e.target.style.borderColor = "#E5E7EB")}
                              />
                              {linkValue.length > 0 && (
                                <div className="absolute right-3.5 top-1/2 -translate-y-1/2">
                                  {isValidLink
                                    ? <CheckCircle2 className="h-4 w-4" style={{ color: "#059669" }} strokeWidth={1.5} />
                                    : <X className="h-4 w-4" style={{ color: "#F43F5E" }} strokeWidth={2} />
                                  }
                                </div>
                              )}
                            </div>
                            {linkValue.length > 0 && !isValidLink && (
                              <p className="text-xs" style={{ color: "#F43F5E" }}>URL must start with https:// or http://</p>
                            )}
                          </div>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>
                </div>

                {/* CTA */}
                <button onClick={handleRun} disabled={!canRun}
                  className="w-full py-3.5 rounded-xl text-sm font-semibold flex items-center justify-center gap-2 transition-all"
                  style={{
                    background: canRun ? "#4F46E5" : "#E5E7EB",
                    color: canRun ? "#FFFFFF" : "#9CA3AF",
                    cursor: canRun ? "pointer" : "not-allowed",
                  }}>
                  <Search className="h-4 w-4" strokeWidth={2} />
                  Run UX Audit
                </button>

                {apiError && <p className="text-center text-xs" style={{ color: "#F43F5E" }}>{apiError}</p>}

                {!canRun && (
                  <p className="text-center text-xs" style={{ color: "#9CA3AF" }}>
                    {!projectName.trim()
                      ? "Enter a project name to continue"
                      : "Upload at least one screen or paste a product link"}
                  </p>
                )}
              </div>
            </motion.div>
          )}

          {/* Running */}
          {phase === "running" && (
            <motion.div key="running" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
              className="flex flex-col items-center justify-center py-32 gap-6 text-center">
              <div className="h-16 w-16 rounded-2xl flex items-center justify-center" style={{ background: "#EEF2FF" }}>
                <Search className="h-7 w-7 animate-pulse" style={{ color: "#6366F1" }} strokeWidth={1.5} />
              </div>
              <div className="space-y-2">
                <p className="text-lg font-semibold" style={{ color: "#0F172A" }}>Analyzing your screens…</p>
                <p className="text-sm" style={{ color: "#6B7280" }}>Evaluating usability, cognitive load, interactions, and system gaps</p>
              </div>
              <div className="flex items-center gap-2 flex-wrap justify-center">
                {["Usability", "Cognitive Load", "Interactions", "Trust & Tone", "System Gaps"].map((label, i) => (
                  <motion.span key={label} initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: i * 0.3 }}
                    className="text-xs px-3 py-1 rounded-full" style={{ background: "#F1F5F9", color: "#6B7280" }}>
                    {label}
                  </motion.span>
                ))}
              </div>
            </motion.div>
          )}

          {/* Results */}
          {phase === "results" && (
            <motion.div key="results" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.2 }} className="space-y-8">

              {/* Title + saved badge */}
              <div className="flex items-start justify-between gap-4">
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <h1 className="text-2xl font-bold" style={{ color: "#0F172A" }}>Audit Complete</h1>
                    {savedProjId && (
                      <span className="text-[10px] font-semibold px-2.5 py-1 rounded-full flex items-center gap-1"
                        style={{ background: "#ECFDF5", color: "#059669", border: "1px solid #A7F3D0" }}>
                        <CheckCircle2 className="h-3 w-3" strokeWidth={2} />
                        Saved to Projects
                      </span>
                    )}
                  </div>
                  <p className="text-sm" style={{ color: "#6B7280" }}>
                    {allIssues.length} issues found across {auditData.length} screen{auditData.length !== 1 ? "s" : ""}
                  </p>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  <button onClick={() => exportExcel(auditData)}
                    className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-medium transition-colors hover:bg-[#F1F5F9]"
                    style={{ border: "1px solid #E5E7EB", color: "#374151" }}>
                    <FileSpreadsheet className="h-3.5 w-3.5" style={{ color: "#059669" }} strokeWidth={1.5} />
                    Excel
                  </button>
                  <button onClick={() => exportPDF(auditData)}
                    className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-medium transition-colors hover:bg-[#F1F5F9]"
                    style={{ border: "1px solid #E5E7EB", color: "#374151" }}>
                    <FileText className="h-3.5 w-3.5" style={{ color: "#DC2626" }} strokeWidth={1.5} />
                    PDF
                  </button>
                  <button onClick={() => { setPhase("setup"); setFiles([]); setAuditData([]); setSavedProjId(null); }}
                    className="text-xs px-4 py-2 rounded-lg transition-colors hover:bg-[#F1F5F9]"
                    style={{ color: "#6B7280", border: "1px solid #E5E7EB" }}>
                    New Audit
                  </button>
                </div>
              </div>

              {/* Stats bar */}
              <div className="grid grid-cols-4 gap-3">
                {[
                  { label: "Screens Audited", value: auditData.length,      accent: false },
                  { label: "Total Issues",    value: allIssues.length,      accent: false },
                  { label: "High Severity",   value: highCount,             accent: true  },
                  { label: "Avg UX Score",    value: `${avgScore}/100`,     accent: false },
                ].map((s, i) => (
                  <div key={i} className="rounded-2xl px-4 py-4" style={{ border: "1px solid #E5E7EB", background: "#FFFFFF" }}>
                    <p className="text-xl font-bold mb-1" style={{ color: s.accent ? "#BE123C" : "#0F172A" }}>{s.value}</p>
                    <p className="text-[11px]" style={{ color: "#6B7280" }}>{s.label}</p>
                  </div>
                ))}
              </div>

              {/* Severity filter */}
              <div className="flex items-center gap-1 rounded-xl p-1 w-fit" style={{ background: "#F1F5F9" }}>
                {(["all", "high", "medium", "low"] as SevFilter[]).map(f => (
                  <button key={f} onClick={() => setSevFilter(f)}
                    className="rounded-lg px-4 py-1.5 text-xs font-medium capitalize transition-all"
                    style={{
                      background: sevFilter === f ? "#FFFFFF" : "transparent",
                      color: sevFilter === f ? "#0F172A" : "#6B7280",
                      boxShadow: sevFilter === f ? "0 1px 3px rgba(0,0,0,0.08)" : "none",
                    }}>
                    {f === "all" ? "All Severity" : f.charAt(0).toUpperCase() + f.slice(1)}
                  </button>
                ))}
              </div>

              {/* Screen cards */}
              <div className="space-y-5">
                {auditData.map(screen => (
                  <ScreenAuditCard
                    key={screen.id}
                    screen={screen}
                    sevFilter={sevFilter}
                    previewUrl={previews[screen.name]}
                  />
                ))}
              </div>

            </motion.div>
          )}

        </AnimatePresence>
      </div>
    </div>
  );
}
