import { useState, useEffect, useRef } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { confirmPhaseReview, runPrompts, type RichPersonaPrompt, type RichSystemPrompt } from "@/lib/api";
import { motion, AnimatePresence } from "framer-motion";
import {
  ArrowLeft, ArrowRight,
  Cpu, FileText, Brain, Upload, BookOpen, Search, Layers,
  Copy, Check, RefreshCw, Download, Pencil, AlertTriangle, Sparkles,
  ExternalLink, ChevronDown, ChevronRight,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import {
  DropdownMenu, DropdownMenuTrigger, DropdownMenuContent,
  DropdownMenuItem, DropdownMenuSeparator, DropdownMenuLabel,
} from "@/components/ui/dropdown-menu";
import { AppSidebar } from "@/components/dashboard/AppSidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { cn } from "@/lib/utils";

// ─── Types ────────────────────────────────────────────────────────────────────

type Format    = "lovable" | "v0" | "generic";
type Verbosity = "detailed" | "short";

interface SystemPromptSection {
  id:      string;
  title:   string;
  content: string;
}

interface PersonaInfluence {
  name:          string;
  role:          string;
  tag:           "Primary" | "Secondary" | "Edge";
  initial:       string;
  keyGoal:       string;
  behaviorTag:   string;
  contributions: string[];
}

interface SystemPrompt {
  quality:           number;
  totalScreens:      number;
  platform:          string;
  sections:          SystemPromptSection[];
  personaInfluences: PersonaInfluence[];
}

interface PromptSection {
  id:      string;
  title:   string;
  content: string;
  hint?:   string;
}

interface PersonaPrompt {
  id:           string;
  name:         string;
  role:         string;
  tag:          "Primary" | "Secondary";
  status:       "generated" | "review";
  initial:      string;
  quality:      number;
  screensCount: number;
  sections:     PromptSection[];
}

// ─── Constants ────────────────────────────────────────────────────────────────

const FORMAT_LABELS: Record<Format, string> = {
  lovable: "Lovable",
  v0:      "v0",
  generic: "Generic AI",
};

const FORMAT_PREFIXES: Record<Format, string> = {
  lovable: "Build this prototype using Lovable.\nStack: React + TypeScript + Tailwind CSS + shadcn/ui.",
  v0:      "Generate this UI using v0 by Vercel.\nStack: Next.js App Router + shadcn/ui + Tailwind CSS.",
  generic: "",
};

// ─── Utilities ────────────────────────────────────────────────────────────────

function buildSystemPromptString(systemPrompt: SystemPrompt, format: Format): string {
  const prefix = FORMAT_PREFIXES[format] ? FORMAT_PREFIXES[format] + "\n\n" : "";
  const body = systemPrompt.sections
    .filter(s => s.content.trim())
    .map(s => `## ${s.title.toUpperCase()}\n${s.content}`)
    .join("\n\n");
  return prefix + body;
}

function buildPersonaPromptString(persona: PersonaPrompt, format: Format, verbosity: Verbosity): string {
  const prefix = FORMAT_PREFIXES[format] ? FORMAT_PREFIXES[format] + "\n\n" : "";
  const body = persona.sections
    .filter(s => s.content.trim())
    .map(s => {
      const content = verbosity === "short" ? s.content.split("\n")[0] : s.content;
      return `## ${s.title.toUpperCase()}\n${content}`;
    })
    .join("\n\n");
  return prefix + body;
}

function exportSystemAsTxt(systemPrompt: SystemPrompt, format: Format) {
  const text = buildSystemPromptString(systemPrompt, format);
  const blob = new Blob([text], { type: "text/plain;charset=utf-8;" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href = url; a.download = "Aether_SystemPrompt.txt"; a.click();
  URL.revokeObjectURL(url);
}

function exportSystemAsMd(systemPrompt: SystemPrompt, format: Format) {
  const prefix   = FORMAT_PREFIXES[format] ? `${FORMAT_PREFIXES[format]}\n\n` : "";
  const sections = systemPrompt.sections
    .filter(s => s.content.trim())
    .map(s => `## ${s.title}\n\n${s.content}`)
    .join("\n\n---\n\n");
  const md = `# Unified Product System Prompt\n_Generated by Aether · ${FORMAT_LABELS[format]} format_\n\n${prefix}${sections}`;
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8;" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href = url; a.download = "Aether_SystemPrompt.md"; a.click();
  URL.revokeObjectURL(url);
}

function qualityColor(score: number) {
  if (score >= 90) return "text-emerald-600 bg-emerald-50 dark:bg-emerald-950/30";
  if (score >= 70) return "text-amber-600 bg-amber-50 dark:bg-amber-950/30";
  return "text-rose-600 bg-rose-50 dark:bg-rose-950/30";
}

// ─── Stage Tracker ────────────────────────────────────────────────────────────

function StageTracker({ current }: { current: number }) {
  const stages = [
    { label: "Upload",    icon: Upload   },
    { label: "Intake",    icon: Brain    },
    { label: "Screens",   icon: Layers   },
    { label: "Prototype", icon: Cpu      },
    { label: "Audit",     icon: Search   },
    { label: "Copy",      icon: FileText },
    { label: "Docs",      icon: BookOpen },
  ];
  return (
    <div className="flex items-center gap-0">
      {stages.map((s, i) => {
        const done   = i < current;
        const active = i === current;
        const locked = i > current;
        return (
          <div key={s.label} className="flex items-center">
            <Tooltip>
              <TooltipTrigger asChild>
                <div className={cn(
                  "flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-medium transition-all",
                  active && "bg-foreground text-background",
                  done   && "text-muted-foreground hover:text-foreground cursor-pointer",
                  locked && "text-muted-foreground/40 cursor-not-allowed",
                )}>
                  <s.icon className="h-3 w-3" strokeWidth={1.5} />
                  <span className="hidden sm:inline">{s.label}</span>
	              </div>
              </TooltipTrigger>
              <TooltipContent side="bottom">{s.label}</TooltipContent>
            </Tooltip>
            {i < stages.length - 1 && (
              <div className={cn("w-4 h-px mx-0.5", i < current ? "bg-foreground/30" : "bg-border")} />
            )}
          </div>
        );
      })}
    </div>
  );
}

// ─── Section Block ────────────────────────────────────────────────────────────

interface SectionBlockProps {
  section:     SystemPromptSection | PromptSection;
  isEditing:   boolean;
  isLast:      boolean;
  onStartEdit: () => void;
  onEndEdit:   () => void;
  onChange:    (content: string) => void;
  hint?:       string;
  verbosity?:  Verbosity;
}

function SectionBlock({ section, isEditing, isLast, onStartEdit, onEndEdit, onChange, hint, verbosity }: SectionBlockProps) {
  const displayContent = verbosity === "short"
    ? section.content.split("\n")[0]
    : section.content;

  return (
    <div className={cn(
      "group px-6 py-5 transition-colors hover:bg-secondary/30",
      !isLast && "border-b border-border/40",
    )}>
      <div className="flex items-center justify-between mb-2.5">
        <span className="text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">
          {section.title}
        </span>
        {!isEditing && (
          <button
            onClick={onStartEdit}
            className="opacity-0 group-hover:opacity-100 flex items-center gap-1 text-[10px] text-muted-foreground hover:text-foreground transition-all rounded-md px-1.5 py-0.5 hover:bg-secondary"
          >
            <Pencil className="h-2.5 w-2.5" strokeWidth={1.5} />
            Edit
          </button>
        )}
      </div>

      {isEditing ? (
        <textarea
          value={section.content}
          onChange={e => onChange(e.target.value)}
          onBlur={onEndEdit}
          autoFocus
          className="w-full text-sm font-mono text-foreground bg-background/60 border border-border/60 rounded-xl px-4 py-3 resize-none outline-none focus:border-foreground/30 transition-colors leading-relaxed"
          rows={Math.max(3, section.content.split("\n").length + 1)}
        />
      ) : (
        <p
          onClick={onStartEdit}
          className={cn(
            "text-sm font-mono leading-relaxed whitespace-pre-wrap cursor-text transition-colors",
            displayContent
              ? "text-foreground/80 hover:text-foreground"
              : "text-muted-foreground/40 italic",
          )}
        >
          {displayContent || "Click to add content…"}
        </p>
      )}

      {hint && !isEditing && (
        <div className="mt-3 flex items-start gap-2 text-[11px] text-amber-600 bg-amber-50 dark:bg-amber-950/20 rounded-lg px-3 py-2 border border-amber-200/60 dark:border-amber-800/30">
          <AlertTriangle className="h-3 w-3 mt-0.5 shrink-0" strokeWidth={1.5} />
          {hint}
        </div>
      )}
    </div>
  );
}

// ─── System Export Menu ───────────────────────────────────────────────────────

interface SystemExportMenuProps {
  systemPrompt: SystemPrompt;
  format:       Format;
  onCopy:       () => void;
  size?:        "sm" | "default";
}

function SystemExportMenu({ systemPrompt, format, onCopy, size = "default" }: SystemExportMenuProps) {
  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button
          variant="outline"
          size={size === "sm" ? "sm" : "default"}
          className={cn(
            "gap-1.5",
            size === "sm" ? "h-8 rounded-lg text-xs" : "h-10 rounded-xl text-sm",
          )}
        >
          <Download className={cn(size === "sm" ? "h-3.5 w-3.5" : "h-4 w-4")} strokeWidth={1.5} />
          Export
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-52">
        <DropdownMenuLabel className="text-[11px] text-muted-foreground font-normal">
          System Prompt
        </DropdownMenuLabel>
        <DropdownMenuItem onClick={onCopy} className="text-xs gap-2">
          <Copy className="h-3.5 w-3.5" strokeWidth={1.5} />
          Copy System Prompt
        </DropdownMenuItem>
        <DropdownMenuSeparator />
        <DropdownMenuItem onClick={() => exportSystemAsTxt(systemPrompt, format)} className="text-xs gap-2">
          <FileText className="h-3.5 w-3.5" strokeWidth={1.5} />
          Export as .txt
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => exportSystemAsMd(systemPrompt, format)} className="text-xs gap-2">
          <FileText className="h-3.5 w-3.5" strokeWidth={1.5} />
          Export as .md
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}

// ─── Mappers ──────────────────────────────────────────────────────────────────

function mapApiToUiPrompts(rich: RichPersonaPrompt[]): PersonaPrompt[] {
  return rich.map(p => ({
    id:           p.id,
    name:         p.name,
    role:         p.role,
    tag:          p.tag as "Primary" | "Secondary",
    status:       p.status as "generated" | "review",
    initial:      p.initial,
    quality:      p.quality,
    screensCount: p.screensCount,
    sections:     p.sections.map(s => ({
      id:      s.id,
      title:   s.title,
      content: s.content,
      hint:    s.hint,
    })),
  }));
}

function mapApiToUiSystemPrompt(raw: RichSystemPrompt): SystemPrompt {
  return {
    quality:      raw.quality,
    totalScreens: raw.totalScreens,
    platform:     raw.platform ?? "Web App",
    sections:     raw.sections.map(s => ({
      id:      s.id,
      title:   s.title,
      content: s.content,
    })),
    personaInfluences: raw.personaInfluences.map(pi => ({
      name:          pi.name,
      role:          pi.role,
      tag:           pi.tag as "Primary" | "Secondary" | "Edge",
      initial:       pi.initial,
      keyGoal:       pi.keyGoal,
      behaviorTag:   pi.behaviorTag,
      contributions: pi.contributions,
    })),
  };
}

// ─── Main Page ────────────────────────────────────────────────────────────────

const PrototypePage = () => {
  const navigate = useNavigate();
  const { id: projectId } = useParams<{ id: string }>();

  const [systemPrompt,       setSystemPrompt]       = useState<SystemPrompt | null>(null);
  const [personaPrompts,     setPersonaPrompts]     = useState<PersonaPrompt[]>([]);
  const [selectedPersonaId,  setSelectedPersonaId]  = useState<string>("");
  const [format,             setFormat]             = useState<Format>("lovable");
  const [verbosity,          setVerbosity]          = useState<Verbosity>("detailed");
  const [editingSection,     setEditingSection]     = useState<string | null>(null);
  const [copied,             setCopied]             = useState(false);
  const [stitchOpened,       setStitchOpened]       = useState(false);
  const [isRegenerating,     setIsRegenerating]     = useState(false);
  const [generating,         setGenerating]         = useState(true);
  const [apiError,           setApiError]           = useState<string | null>(null);
  const [finalizeError,      setFinalizeError]      = useState<string | null>(null);
  const [isFinalizing,       setIsFinalizing]       = useState(false);
  const [influenceOpen,      setInfluenceOpen]      = useState(false);
  const [personaPromptsOpen, setPersonaPromptsOpen] = useState(false);
  const requestRef = useRef<AbortController | null>(null);

  const cancelPromptRequest = () => {
    requestRef.current?.abort();
    requestRef.current = null;
    setGenerating(false);
    setIsRegenerating(false);
    setApiError("Generation cancelled.");
  };

  const startPromptRequest = () => {
    requestRef.current?.abort();
    const controller = new AbortController();
    requestRef.current = controller;
    return controller;
  };

  useEffect(() => {
    if (!projectId) return;
    const controller = startPromptRequest();
    setGenerating(true);
    setApiError(null);
    runPrompts(projectId, false, controller.signal)
      .then(res => {
        if (controller.signal.aborted) return;
        const mapped = mapApiToUiPrompts(res.prompts_rich);
        setPersonaPrompts(mapped);
        if (mapped.length > 0) setSelectedPersonaId(mapped[0].id);
        if (res.system_prompt) setSystemPrompt(mapApiToUiSystemPrompt(res.system_prompt));
      })
      .catch(err => {
        if (!controller.signal.aborted) {
          setApiError(err?.message ?? "Failed to load prompts.");
        }
      })
      .finally(() => {
        if (!controller.signal.aborted) {
          setGenerating(false);
          if (requestRef.current === controller) requestRef.current = null;
        }
      });
    return () => controller.abort();
  }, [projectId]);

  const currentPersona = personaPrompts.find(p => p.id === selectedPersonaId) ?? personaPrompts[0];
  const totalScreens   = systemPrompt?.totalScreens ?? personaPrompts.reduce((a, p) => a + p.screensCount, 0);

  const handleCopySystem = () => {
    if (!systemPrompt) return;
    navigator.clipboard.writeText(buildSystemPromptString(systemPrompt, format));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleGenerateInStitch = () => {
    if (!systemPrompt) return;
    navigator.clipboard.writeText(buildSystemPromptString(systemPrompt, format));
    setStitchOpened(true);
    setTimeout(() => setStitchOpened(false), 2500);
    window.open("https://stitch.withgoogle.com", "_blank", "noopener,noreferrer");
  };

  const handleRegenerate = () => {
    if (!projectId) return;
    const controller = startPromptRequest();
    setIsRegenerating(true);
    setEditingSection(null);
    setApiError(null);
    runPrompts(projectId, true, controller.signal)
      .then(res => {
        if (controller.signal.aborted) return;
        const mapped = mapApiToUiPrompts(res.prompts_rich);
        setPersonaPrompts(mapped);
        if (mapped.length > 0) setSelectedPersonaId(mapped[0].id);
        if (res.system_prompt) setSystemPrompt(mapApiToUiSystemPrompt(res.system_prompt));
      })
      .catch(err => {
        if (!controller.signal.aborted) {
          setApiError(err?.message ?? "Regeneration failed");
        }
      })
      .finally(() => {
        if (!controller.signal.aborted) {
          setIsRegenerating(false);
          if (requestRef.current === controller) requestRef.current = null;
        }
      });
  };

  const handleProceed = async () => {
    if (!projectId) {
      navigate("/dashboard");
      return;
    }

    try {
      setIsFinalizing(true);
      setFinalizeError(null);
      await confirmPhaseReview(projectId, 3, {
        nextPhase: 4,
        summary: "Prototype prompts reviewed and approved for audit.",
        metrics: {
          persona_count: personaPrompts.length,
          section_count: systemPrompt.sections.length,
          total_screens: totalScreens,
          system_quality: systemPrompt.quality,
        },
      });
      navigate(`/project/${projectId}/phase/04`);
    } catch (error) {
      setFinalizeError(error instanceof Error ? error.message : "Unable to confirm this phase right now.");
    } finally {
      setIsFinalizing(false);
    }
  };

  const updateSystemSection = (sectionId: string, content: string) => {
    setSystemPrompt(prev => prev ? {
      ...prev,
      sections: prev.sections.map(s => s.id === sectionId ? { ...s, content } : s),
    } : prev);
  };

  const updatePersonaSection = (sectionId: string, content: string) => {
    setPersonaPrompts(prev => prev.map(p =>
      p.id === selectedPersonaId
        ? { ...p, sections: p.sections.map(s => s.id === sectionId ? { ...s, content } : s) }
        : p,
    ));
  };

  // ── Loading ──
  if (generating) return (
    <SidebarProvider>
      <div className="min-h-screen flex w-full bg-background">
        <AppSidebar />
        <div className="flex-1 flex flex-col items-center justify-center gap-4">
          <div className="h-10 w-10 rounded-xl bg-accent/10 flex items-center justify-center">
            <Sparkles className="h-5 w-5 text-accent animate-pulse" strokeWidth={1.5} />
          </div>
          <div className="text-center">
            <p className="text-sm font-medium text-foreground">Building your product system…</p>
            <p className="text-xs text-muted-foreground mt-1">Synthesizing all personas into one unified system prompt. 20–40 seconds.</p>
          </div>
          <div className="flex gap-1 mt-2">
            {[0, 1, 2].map(i => (
              <div key={i} className="h-1.5 w-1.5 rounded-full bg-accent/40 animate-bounce" style={{ animationDelay: `${i * 0.15}s` }} />
            ))}
          </div>
          <Button variant="outline" size="sm" onClick={cancelPromptRequest} className="rounded-xl text-xs gap-1.5">
            Cancel Generation
          </Button>
        </div>
      </div>
    </SidebarProvider>
  );

  // ── Error ──
  if (apiError) return (
    <SidebarProvider>
      <div className="min-h-screen flex w-full bg-background">
        <AppSidebar />
        <div className="flex-1 flex flex-col items-center justify-center gap-4 max-w-md mx-auto text-center px-6">
          <div className="h-10 w-10 rounded-xl bg-destructive/10 flex items-center justify-center">
            <AlertTriangle className="h-5 w-5 text-destructive" strokeWidth={1.5} />
          </div>
          <div>
            <p className="text-sm font-medium text-foreground">System prompt generation failed</p>
            <p className="text-xs text-muted-foreground mt-1 leading-relaxed">{apiError}</p>
          </div>
          <Button size="sm" className="rounded-xl gradient-accent text-accent-foreground text-xs gap-1.5" onClick={handleRegenerate}>
            <RefreshCw className="h-3.5 w-3.5" strokeWidth={1.5} />
            Retry
          </Button>
        </div>
      </div>
    </SidebarProvider>
  );

  if (!systemPrompt) return null;

  return (
    <SidebarProvider>
      <div className="flex h-screen w-full overflow-hidden bg-background">
        <AppSidebar />
        <div className="flex flex-col flex-1 overflow-hidden">

          {/* ── Header ── */}
          <header className="h-14 flex items-center border-b border-border px-6 gap-3 shrink-0 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/80">
            <SidebarTrigger className="text-muted-foreground hover:text-foreground shrink-0" />
            <div className="h-4 w-px bg-border shrink-0" />
            <span className="text-sm font-semibold text-foreground">Aether Platform</span>
            <div className="h-4 w-px bg-border shrink-0 hidden sm:block" />
            <span className="text-xs font-medium text-foreground hidden sm:block">Phase 03</span>
            <span className="text-xs text-muted-foreground hidden md:block">— Prototype Prompts</span>

            <div className="ml-auto flex items-center gap-2 shrink-0">
              <Button variant="ghost" size="sm"
                onClick={() => navigate(projectId ? `/project/${projectId}/phase/02` : "/dashboard")}
                className="h-8 rounded-lg text-xs gap-1.5">
                <ArrowLeft className="h-3.5 w-3.5" strokeWidth={1.5} />
                Back to Screen Derivation
              </Button>
              <SystemExportMenu systemPrompt={systemPrompt} format={format} onCopy={handleCopySystem} size="sm" />
              <Button size="sm"
                onClick={handleProceed}
                disabled={isFinalizing}
                className="h-8 rounded-lg text-xs gap-1.5 gradient-accent text-accent-foreground hover:brightness-110 shadow-soft">
                {isFinalizing ? "Confirming..." : "Proceed to UX Audit"}
                <ArrowRight className="h-3.5 w-3.5" strokeWidth={1.5} />
              </Button>
            </div>
          </header>

          {/* ── Stage Tracker + Stats ── */}
          <div className="border-b border-border/60 px-6 py-3 space-y-3 shrink-0">
            <StageTracker current={3} />
            <div className="flex items-center gap-5">
              <div className="flex items-center gap-1.5">
                <span className="text-lg font-bold text-foreground">{personaPrompts.length}</span>
                <span className="text-[10px] text-muted-foreground uppercase tracking-wide">Personas</span>
              </div>
              <div className="h-3 w-px bg-border/60" />
              <div className="flex items-center gap-1.5">
                <span className="text-lg font-bold text-foreground">{totalScreens}</span>
                <span className="text-[10px] text-muted-foreground uppercase tracking-wide">Screens Covered</span>
              </div>
              <div className="h-3 w-px bg-border/60" />
              <div className="flex items-center gap-1.5">
                <span className={cn(
                  "text-lg font-bold",
                  systemPrompt.quality >= 90 ? "text-emerald-600" : systemPrompt.quality >= 70 ? "text-amber-600" : "text-rose-600",
                )}>
                  {systemPrompt.quality}%
                </span>
                <span className="text-[10px] text-muted-foreground uppercase tracking-wide">System Quality</span>
              </div>
              <div className="h-3 w-px bg-border/60" />
              <div className="flex items-center gap-1.5">
                <span className="text-lg font-bold text-foreground">{systemPrompt.sections.length}</span>
                <span className="text-[10px] text-muted-foreground uppercase tracking-wide">Sections</span>
              </div>
              <div className="h-3 w-px bg-border/60" />
              <div className="flex items-center gap-1.5">
                <span className="text-[10px] font-semibold text-foreground">{systemPrompt.platform}</span>
              </div>
            </div>
          </div>

          {/* ── Main Split Layout ── */}
          <div className="flex flex-1 overflow-hidden">

            {/* ── Left: Persona Intelligence ── */}
            <div className="w-64 shrink-0 border-r border-border/60 overflow-y-auto py-4 px-3 flex flex-col gap-2">
              <p className="text-[10px] font-semibold uppercase tracking-widest text-muted-foreground px-2 mb-1">
                Persona Intelligence
              </p>
              {systemPrompt.personaInfluences.map(pi => (
                <div key={pi.name} className="w-full rounded-xl px-3 py-3 border border-border/40 bg-secondary/20">
                  <div className="flex items-start gap-2.5">
                    <div className="h-8 w-8 rounded-lg flex items-center justify-center text-[11px] font-bold shrink-0 bg-foreground/8 text-foreground">
                      {pi.initial}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-1.5 flex-wrap">
                        <span className="text-xs font-semibold text-foreground truncate">{pi.name}</span>
                        <span className={cn(
                          "text-[9px] font-semibold px-1.5 py-0.5 rounded-full",
                          pi.tag === "Primary"
                            ? "bg-foreground/10 text-foreground"
                            : "bg-secondary text-muted-foreground",
                        )}>
                          {pi.tag}
                        </span>
                      </div>
                      <p className="text-[11px] text-muted-foreground mt-0.5 truncate">{pi.role}</p>
                      <p className="text-[11px] text-foreground/70 mt-1 leading-snug line-clamp-2">{pi.keyGoal}</p>
                      <span className="inline-block mt-1.5 text-[9px] font-medium px-1.5 py-0.5 rounded-full bg-accent/10 text-accent">
                        {pi.behaviorTag}
                      </span>
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {/* ── Right: System Prompt Workspace ── */}
            <div className="flex-1 flex flex-col overflow-hidden">

              {/* Toolbar */}
              <div className="shrink-0 border-b border-border/60 px-6 py-3 flex items-center gap-3 flex-wrap bg-background/50">
                <div className="flex items-center gap-1 rounded-xl bg-secondary p-1">
                  {(["lovable", "v0", "generic"] as Format[]).map(f => (
                    <button key={f} onClick={() => setFormat(f)}
                      className={cn(
                        "rounded-lg px-3 py-1 text-xs font-medium transition-colors",
                        format === f
                          ? "bg-background text-foreground shadow-sm"
                          : "text-muted-foreground hover:text-foreground",
                      )}>
                      {FORMAT_LABELS[f]}
                    </button>
                  ))}
                </div>

                <div className="ml-auto flex items-center gap-2">
                  <Button variant="ghost" size="sm" onClick={handleRegenerate} disabled={isRegenerating}
                    className="h-8 rounded-lg text-xs gap-1.5 text-muted-foreground hover:text-foreground">
                    <RefreshCw className={cn("h-3.5 w-3.5", isRegenerating && "animate-spin")} strokeWidth={1.5} />
                    {isRegenerating ? "Regenerating…" : "Regenerate"}
                  </Button>

                  <Button size="sm" variant="outline" onClick={handleGenerateInStitch}
                    className={cn(
                      "h-8 rounded-lg text-xs gap-1.5 transition-all",
                      stitchOpened && "border-violet-400 text-violet-600",
                    )}>
                    {stitchOpened
                      ? <Check className="h-3.5 w-3.5" strokeWidth={2} />
                      : <ExternalLink className="h-3.5 w-3.5" strokeWidth={1.5} />
                    }
                    {stitchOpened ? "Prompt Copied!" : "Build Prototype"}
                  </Button>

                  <Button size="sm" onClick={handleCopySystem}
                    className={cn(
                      "h-8 rounded-lg text-xs gap-1.5 transition-all",
                      copied
                        ? "bg-emerald-600 hover:bg-emerald-600 text-white"
                        : "gradient-accent text-accent-foreground hover:brightness-110 shadow-soft",
                    )}>
                    {copied
                      ? <Check className="h-3.5 w-3.5" strokeWidth={2} />
                      : <Copy className="h-3.5 w-3.5" strokeWidth={1.5} />
                    }
                    {copied ? "Copied!" : "Copy System Prompt"}
                  </Button>
                </div>
              </div>

              {/* Content */}
              <div className="flex-1 overflow-y-auto">
                <div className="max-w-3xl mx-auto px-6 py-6 space-y-5">
                  <AnimatePresence mode="wait">

                    {isRegenerating ? (
                      <motion.div key="loading"
                        initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                        className="flex flex-col items-center justify-center py-24 gap-4 text-muted-foreground">
                        <RefreshCw className="h-8 w-8 animate-spin" strokeWidth={1} />
                        <Button variant="outline" size="sm" onClick={cancelPromptRequest} className="rounded-xl text-xs gap-1.5">
                          Cancel Regeneration
                        </Button>
                        <p className="text-sm">Rebuilding your product system…</p>
                      </motion.div>
                    ) : (
                      <motion.div key="content"
                        initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0 }} transition={{ duration: 0.15 }}
                        className="space-y-5">

                        {/* ── Primary: Unified System Prompt ── */}
                        <div>
                          <div className="mb-4 flex items-start justify-between gap-4">
                            <div>
                              <h2 className="text-base font-semibold text-foreground">Unified Product System Prompt</h2>
                              <p className="text-xs text-muted-foreground mt-0.5">
                                Generated by combining all personas, journeys, and system flows
                              </p>
                            </div>
                            <span className={cn("text-[10px] font-semibold px-2 py-1 rounded-full shrink-0", qualityColor(systemPrompt.quality))}>
                              System Quality {systemPrompt.quality}%
                            </span>
                          </div>

                          {FORMAT_PREFIXES[format] && (
                            <div className="mb-4 px-4 py-3 rounded-xl bg-accent/8 border border-accent/20">
                              <p className="text-[11px] font-mono text-accent whitespace-pre-wrap leading-relaxed">
                                {FORMAT_PREFIXES[format]}
                              </p>
                            </div>
                          )}

                          <div className="rounded-2xl border border-border/60 overflow-hidden bg-secondary/20 shadow-sm">
                            {systemPrompt.sections.map((section, idx) => (
                              <SectionBlock
                                key={section.id}
                                section={section}
                                isEditing={editingSection === section.id}
                                isLast={idx === systemPrompt.sections.length - 1}
                                onStartEdit={() => setEditingSection(section.id)}
                                onEndEdit={() => setEditingSection(null)}
                                onChange={content => updateSystemSection(section.id, content)}
                              />
                            ))}
                          </div>
                        </div>

                        {/* ── Collapsible: Persona Influence ── */}
                        <div className="rounded-2xl border border-border/60 overflow-hidden">
                          <button
                            onClick={() => setInfluenceOpen(v => !v)}
                            className="w-full flex items-center justify-between px-5 py-4 hover:bg-secondary/40 transition-colors"
                          >
                            <div className="text-left">
                              <p className="text-sm font-semibold text-foreground">How personas shaped this system</p>
                              <p className="text-[11px] text-muted-foreground mt-0.5">
                                {systemPrompt.personaInfluences.length} personas · {systemPrompt.personaInfluences.reduce((a, pi) => a + pi.contributions.length, 0)} contributions
                              </p>
                            </div>
                            {influenceOpen
                              ? <ChevronDown className="h-4 w-4 text-muted-foreground shrink-0" strokeWidth={1.5} />
                              : <ChevronRight className="h-4 w-4 text-muted-foreground shrink-0" strokeWidth={1.5} />
                            }
                          </button>

                          <AnimatePresence>
                            {influenceOpen && (
                              <motion.div
                                initial={{ height: 0, opacity: 0 }}
                                animate={{ height: "auto", opacity: 1 }}
                                exit={{ height: 0, opacity: 0 }}
                                transition={{ duration: 0.2 }}
                                className="overflow-hidden border-t border-border/60"
                              >
                                <div className="px-5 py-4 grid grid-cols-1 gap-3">
                                  {systemPrompt.personaInfluences.map(pi => (
                                    <div key={pi.name} className="flex items-start gap-3 p-3 rounded-xl bg-secondary/30 border border-border/40">
                                      <div className="h-8 w-8 rounded-lg flex items-center justify-center text-[11px] font-bold shrink-0 bg-foreground/8 text-foreground">
                                        {pi.initial}
                                      </div>
                                      <div className="flex-1 min-w-0">
                                        <div className="flex items-center gap-2 mb-1.5">
                                          <span className="text-xs font-semibold text-foreground">{pi.name}</span>
                                          <span className="text-[9px] font-medium px-1.5 py-0.5 rounded-full bg-accent/10 text-accent">
                                            {pi.behaviorTag}
                                          </span>
                                        </div>
                                        <ul className="space-y-1">
                                          {pi.contributions.map((c, i) => (
                                            <li key={i} className="flex items-start gap-1.5 text-[11px] text-foreground/70">
                                              <span className="text-accent mt-0.5 shrink-0">→</span>
                                              {c}
                                            </li>
                                          ))}
                                        </ul>
                                      </div>
                                    </div>
                                  ))}
                                </div>
                              </motion.div>
                            )}
                          </AnimatePresence>
                        </div>

                        {/* ── Collapsible: Persona-Level Prompts ── */}
                        <div className="rounded-2xl border border-border/60 overflow-hidden">
                          <button
                            onClick={() => setPersonaPromptsOpen(v => !v)}
                            className="w-full flex items-center justify-between px-5 py-4 hover:bg-secondary/40 transition-colors"
                          >
                            <div className="text-left">
                              <p className="text-sm font-semibold text-foreground">View Persona-Level Prompts</p>
                              <p className="text-[11px] text-muted-foreground mt-0.5">
                                {personaPrompts.length} individual prompts · Advanced / debug view
                              </p>
                            </div>
                            {personaPromptsOpen
                              ? <ChevronDown className="h-4 w-4 text-muted-foreground shrink-0" strokeWidth={1.5} />
                              : <ChevronRight className="h-4 w-4 text-muted-foreground shrink-0" strokeWidth={1.5} />
                            }
                          </button>

                          <AnimatePresence>
                            {personaPromptsOpen && currentPersona && (
                              <motion.div
                                initial={{ height: 0, opacity: 0 }}
                                animate={{ height: "auto", opacity: 1 }}
                                exit={{ height: 0, opacity: 0 }}
                                transition={{ duration: 0.2 }}
                                className="overflow-hidden border-t border-border/60"
                              >
                                <div className="p-5 space-y-4">
                                  {/* Persona tabs */}
                                  <div className="flex gap-1.5 flex-wrap">
                                    {personaPrompts.map(p => (
                                      <button
                                        key={p.id}
                                        onClick={() => { setSelectedPersonaId(p.id); setEditingSection(null); }}
                                        className={cn(
                                          "flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium transition-colors border",
                                          selectedPersonaId === p.id
                                            ? "bg-foreground text-background border-foreground"
                                            : "border-border text-muted-foreground hover:text-foreground hover:border-foreground/30",
                                        )}
                                      >
                                        <span className="h-4 w-4 rounded flex items-center justify-center text-[9px] font-bold">
                                          {p.initial}
                                        </span>
                                        {p.name}
                                        <span className={cn("text-[9px] font-semibold px-1 py-0.5 rounded-full", qualityColor(p.quality))}>
                                          {p.quality}%
                                        </span>
                                      </button>
                                    ))}
                                  </div>

                                  {/* Verbosity toggle */}
                                  <div className="flex items-center gap-2">
                                    <span className="text-[10px] text-muted-foreground uppercase tracking-wide">Verbosity</span>
                                    <div className="flex items-center gap-1 rounded-xl bg-secondary p-1">
                                      {(["detailed", "short"] as Verbosity[]).map(v => (
                                        <button key={v} onClick={() => setVerbosity(v)}
                                          className={cn(
                                            "rounded-lg px-3 py-1 text-xs font-medium capitalize transition-colors",
                                            verbosity === v
                                              ? "bg-background text-foreground shadow-sm"
                                              : "text-muted-foreground hover:text-foreground",
                                          )}>
                                          {v}
                                        </button>
                                      ))}
                                    </div>
                                  </div>

                                  {/* Persona prompt */}
                                  <div>
                                    <div className="mb-3 flex items-start justify-between gap-4">
                                      <div>
                                        <div className="flex items-center gap-2 mb-0.5">
                                          <h3 className="text-sm font-semibold text-foreground">{currentPersona.name}</h3>
                                          <span className="text-xs text-muted-foreground">· {currentPersona.role}</span>
                                        </div>
                                        <p className="text-xs text-muted-foreground">
                                          {currentPersona.screensCount} screens · {FORMAT_LABELS[format]} format · {verbosity}
                                        </p>
                                      </div>
                                      <button
                                        onClick={() => {
                                          navigator.clipboard.writeText(buildPersonaPromptString(currentPersona, format, verbosity));
                                        }}
                                        className="flex items-center gap-1 text-[10px] text-muted-foreground hover:text-foreground transition-colors rounded-md px-2 py-1 hover:bg-secondary border border-border"
                                      >
                                        <Copy className="h-2.5 w-2.5" strokeWidth={1.5} />
                                        Copy
                                      </button>
                                    </div>
                                    <div className="rounded-2xl border border-border/60 overflow-hidden bg-secondary/20">
                                      {currentPersona.sections.map((section, idx) => (
                                        <SectionBlock
                                          key={section.id}
                                          section={section}
                                          isEditing={editingSection === `persona-${section.id}`}
                                          isLast={idx === currentPersona.sections.length - 1}
                                          onStartEdit={() => setEditingSection(`persona-${section.id}`)}
                                          onEndEdit={() => setEditingSection(null)}
                                          onChange={content => updatePersonaSection(section.id, content)}
                                          hint={section.hint}
                                          verbosity={verbosity}
                                        />
                                      ))}
                                    </div>
                                  </div>
                                </div>
                              </motion.div>
                            )}
                          </AnimatePresence>
                        </div>

                      </motion.div>
                    )}

                  </AnimatePresence>
                </div>
              </div>

            </div>
          </div>

          {/* ── Bottom CTA ── */}
          <div className="shrink-0 border-t border-border bg-background/95 backdrop-blur px-6 py-4">
            <div className="max-w-5xl mx-auto flex items-center justify-between gap-4 flex-wrap">
              <div className="space-y-0.5">
                <p className="text-sm font-medium text-foreground">Your product system is ready</p>
                <p className="text-xs text-muted-foreground">
                  System prompt ready · Covers {totalScreens} screens · {personaPrompts.length} personas integrated
                </p>
              </div>
              <div className="flex items-center gap-2">
                <SystemExportMenu systemPrompt={systemPrompt} format={format} onCopy={handleCopySystem} />
                <Button variant="outline" onClick={handleGenerateInStitch}
                  className={cn(
                    "h-10 rounded-xl text-sm gap-1.5 transition-all",
                    stitchOpened && "border-violet-400 text-violet-600",
                  )}>
                  {stitchOpened
                    ? <Check className="h-4 w-4" strokeWidth={2} />
                    : <ExternalLink className="h-4 w-4" strokeWidth={1.5} />
                  }
                  {stitchOpened ? "Prompt Copied!" : "Build Prototype"}
                </Button>
                <Button
                  onClick={handleProceed}
                  disabled={isFinalizing}
                  className="h-10 rounded-xl text-sm gap-1.5 gradient-accent text-accent-foreground hover:brightness-110 shadow-soft"
                >
                  {isFinalizing ? "Confirming..." : "Proceed to UX Audit"}
                  <ArrowRight className="h-4 w-4" strokeWidth={1.5} />
                </Button>
              </div>
            </div>
          </div>

        </div>
      </div>
    </SidebarProvider>
  );
};

export default PrototypePage;
